# Generated by Django 5.1.6 on 2025-02-19 06:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_furniture_order_orderitem_delete_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="furniture",
        ),
        migrations.AddField(
            model_name="furniture",
            name="category",
            field=models.CharField(
                choices=[
                    ("chair", "Chair"),
                    ("sofa", "Sofa"),
                    ("table", "Table"),
                    ("bed", "Bed"),
                    ("cabinet", "Cabinet"),
                ],
                default=django.utils.timezone.now,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="furniture",
            name="dimensions",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="Example: 100x50x40 cm",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="furniture",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "furniture",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.furniture"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
