# Generated by Django 5.1.6 on 2025-02-19 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_order_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="furniture",
            name="stock",
        ),
        migrations.AlterField(
            model_name="inventory",
            name="furniture",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory",
                to="api.furniture",
            ),
        ),
    ]
